### ISSUE TITLE
meocloud init error

### ISSUE THREAD

**Issue by lapinpt** [jfhenriques/meocloud-upload#1]
https://meocloud.pt/oauth2/authorize?response_type=code&client_id=*

PIN: *
meocloud: malloc.c:2451: sYSMALLOc: Assertion `(old_top == (((mbinptr) (((char *) &((av)->bins[((1) - 1) \* 2])) - __builtin_offsetof (struct malloc_chunk, fd)))) && old_size == 0) || ((unsigned long) (old_size) >= (unsigned long)((((__builtin_offsetof (struct malloc_chunk, fd_nextsize))+((2 \* (sizeof(size_t))) - 1)) & ~((2 \* (sizeof(size_t))) - 1))) && ((old_top)->size & 0x1) && ((unsigned long)old_end & pagemask) == 0)' failed.
Aborted

**Comment by jfhenriques** [comment]
Seria possível dar mais informação de qual o sistema operativo e arquitectura do processador? Tentei recriar em Windows e Linux e não consigo reproduzir.

**Comment by lapinpt** [comment]
Ubuntu Linux 12.04.4
Linux 3.2.0-69-generic on x86_64

**Comment by jfhenriques** [comment]
Fiz o teste com o linux 12.04.5 numa máquina virtual e não consigo replicar este erro.

Não sei se está relacionado, para o libcurl escolhi o pacote "libcurl4-openssl-dev"

No entanto, estou a trabalhar numa nova versão da aplicação, que poderá resolver este problema.

EDIT:

A flag --debug poderá dar mais detalhes para ajudar a despistar o erro.
