### ISSUE TITLE
Compilação em FreeBSD

### ISSUE THREAD

**Issue by nunotexbsd** [jfhenriques/meocloud-upload#2]
Olá,

Procuro um cliente para Meo Cloud que funcione em UNIX.

Tentei compilar o meocloud-upload em FreeBSD 12.2 amd64 com gcc 9.3.0 e obtenho o seguinte resultado: [output.log](https://termbin.com/w7kh)

Consigo aceder ao serviço Meo através de browser, mas procuro um cliente para o efeito.

Obrigado,

Nuno Teixeira

**Comment by jfhenriques** [comment]
Nunca tinha repado neste issue. Dois anos depos, chegou a conseguir ter algum sucesso? Se tiver interesse em utilizar através do docker, tenho aqui https://github.com/jfhenriques/auto-backup/blob/master/Dockerfile um Dockerfile que na primeira etapa faz build deste projecto, e pode sempre utilizar com docker run --rm meocloud ...

**Comment by nunotexbsd** [comment]
Olá!

Sim já lá vão 2 anos :)

Na altura precisava de um cliente cli (linha de comandos) para acesso ao espaço da cloud mas estretanto deixei de a usar e ainda hoje não faço uso de clouds.

Obrigado
